### ISSUE TITLE
[FEAT] Allow replay of test events

### ISSUE THREAD

**Issue by chadwithuhc** [Team-TAU/tau#100]
**Is your feature request related to a problem? Please describe.**
When I run a test event and it shows up the in Websocket Stream list, I cannot replay it. Only actual events can be replayed.

**Describe the solution you'd like**
I'd like the ability to replay an event no matter what type it is (test or actual).

**Describe alternatives you've considered**
None

https://user-images.githubusercontent.com/259196/167050005-af81e12a-3ee3-45a7-8c50-6ad4867ac793.mp4

**Comment by FiniteSingularity** [comment]
Hi @chadwithuhc .  We can definitely look into this.  However, know that test events are not stored in the database, and are only generated/fired off client-side from the dashboard code.  So we'd be able to add a "replay" button, but once you refresh the dashboard, the test event would go away (and so too would the replay).  I'll take at how to get this implemented later this week.

**Comment by FiniteSingularity** [comment]
@chadwithuhc - Just merged a PR into main that implements this.
