### ISSUE TITLE
[BUG] running "docker-compose up" returns lots of errors about bash being a bad interpreter because of ^M

### ISSUE THREAD

**Issue by iandouglas** [Team-TAU/tau#116]
**Describe the bug**
When starting out fresh with tau as of today's build, running "docker-compose-up" fails with a ^M character attached to a reference to /bin/bash

**To Reproduce**
1. clone the repo on Windows
2. set up .env
3. run "docker-compose up"
4. see lots of this:
```bash
bash: ./scripts/start.sh: /bin/bash^M: bad interpreter: No such file or directory
```

**Expected behavior**
Expect to NOT see this error and see something indicating that it all started successfully?

**Screenshots**
![image](https://user-images.githubusercontent.com/168030/183471961-667beb9b-6a91-4006-a377-5a2ffae40993.png)

**Deployment:**

* Docker Version: Docker version 20.10.17, build 100c701
* Docker Compose Version (if applicable): docker-compose version 1.29.2, build 5becea4c
* Deployment Type: Local
* Deployment Details: n/a

**Additional context**
First time user

**Comment by iandouglas** [comment]
Running "dos2unix" on the script, and removing all containers and storage from Docker Desktop then throws an error about this instead:

![image](https://user-images.githubusercontent.com/168030/183473301-10763d26-465e-4e4e-8230-ff6cb1771179.png)

**Comment by iandouglas** [comment]
You can use `cat -vte` to see line endings, etc:

```bash
 $ cat -vte manage.py | head
#!/usr/bin/env python^M$
"""Django's command-line utility for administrative tasks."""^M$
import os^M$
import sys^M$
```

**Comment by iandouglas** [comment]
Ran `dos2unix` on the manage.py and wait_for_postgres.py and things seem to be working better now.
![image](https://user-images.githubusercontent.com/168030/183474208-c3eb8951-21db-4652-b4f7-a8134f9356c7.png)

**Comment by iandouglas** [comment]
FWIW, it's possible that this is a Windows "git" command issue that converts LF to CRLF, and not sure if that's correctable by the deployment process or if I just need to do better with my Git setup ...

**Comment by FiniteSingularity** [comment]
Hi @iandouglas.  Thank you for the issue.  Yes, there is an issue with how windows git treats line endings, and it causes exactly the same behavior that you're seeing.  I could have sworn that we had this in the documentation, but upon looking, I am not finding it.  I'll need to update the docs to indicate this.

The way to fix it, is set git's `autocrlf` to `false` for windows installs, e.g.:

```
git config core.autocrlf false
```

This will keep git windows from converting the line-endings to windows line-endings.  Another (preferred) option, is to do everything in WSL, as even docker performs significantly better when run from WSL these days.
