### ISSUE TITLE
[BUG] tau_app won't start - possibly an issue with a migration for scopes

### ISSUE THREAD

**Issue by mtfoley** [Team-TAU/tau#75]
**Describe the bug**
It's been a while since I updated my local copy and it seems like there's a migration that didn't apply right.  When I try to do `docker compose up --build`, I get this error as tau_app can't start up.

I've tried pruning basically everything from docker and making sure my .env file has all the same variables as the sample; same result.

![Screen Shot 2021-07-17 at 8 30 45 AM](https://user-images.githubusercontent.com/3792749/126037411-2b8ea523-a632-4aa0-b851-6ba506d0eda6.png)

**Comment by FiniteSingularity** [comment]
Thanks for the bug report @mtfoley .   It looks like somehow your instance of TAU does not have the proper setup of the constance variables.  Is this on a fresh install?  Or an existing install?

**Comment by mtfoley** [comment]
Existing, sort of. I’ve tried deleting all docker images/volumes/containers and running “docker compose up —build” after pulling latest repo but no luck. So the only thing I’m keeping is the .env and I have made sure that I have at least all the same vars as those in the sample file.

**Comment by FiniteSingularity** [comment]
It is a problem with how postgres runs migrations.  There is a constance database migration (`database.0002_auto_20190129_2304`) that must be run before the `core.0001_scope_update_for_chat` migration.  Adding the database migration as a dependency for the scope update migration fixes the issue.  Pushing a PR shortly.
